server:
  port: 8080

jwt.secret: ${JWT_SECRET:prod}

# Database configuration flags
DATABASE_TYPE: ${DATABASE_TYPE:h2}  # h2 or mysql

# Common datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLE:false}
      path: /h2-console
      settings:
        webAllowOthers: true
        autostart: true
  boot:
    admin:
      client:
        url: ${ADMIN_CLIENT_URL:url}
        enable: ${ADMIN_CLIENT_ENABLE:false}
        auto-registration: true
        instance:
          name: ${spring.application.name:Dns-manager}

# actuator
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

# -----------------------------------H2 specific configuration-----------------------------------

# H2_DB: '/etc/dns-manager/db/h2'
# H2_USERNAME: 'sa'
# H2_PASSWORD: 'password'
# H2_CONSOLE_ENABLE: true
# H2_CONSOLE_PATH: '/h2-console'

# spring:
#   datasource:
#     url: jdbc:h2:file:${H2_DB:/etc/dns-manager/db/h2};DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE;CACHE_SIZE=8192;MAX_MEMORY_ROWS=10000;MV_STORE=TRUE;PAGE_SIZE=1024;COMPRESS=TRUE
#     driverClassName: org.h2.Driver
#     username: ${H2_USERNAME:sa}
#     password: ${H2_PASSWORD:password}
#     platform: h2
#   jpa:
#     database-platform: org.hibernate.dialect.H2Dialect
#   h2:
#     console:
#       enabled: ${H2_CONSOLE:true}
#       path: /h2-console
#       settings:
#         webAllowOthers: true
#         autostart: true
#     settings:
#       cacheSizeMax: 8192
#       maxMemoryRows: 10000
#       mvStore: true
#       compressData: true

# -----------------------------------MySQL specific configuration-----------------------------------

# MYSQL_HOST: 'localhost'
# MYSQL_PORT: 3306
# MYSQL_DB: 'dns-manager'
# MYSQL_USERNAME: 'dns-manager'
# MYSQL_PASSWORD: 'password'
# MYSQL_USE_SSL: 'false'

# spring:
#   config:
#     activate:
#       on-profile: mysql
#   datasource:
#     url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:dns-manager}?useSSL=${MYSQL_USE_SSL:false}&allowPublicKeyRetrieval=${MYSQL_ALLOW_PUBLIC_KEY:true}
#     driverClassName: com.mysql.cj.jdbc.Driver
#     username: ${MYSQL_USERNAME:dns-manager}
#     password: ${MYSQL_PASSWORD:password}
#     platform: mysql
#   jpa:
#     database-platform: org.hibernate.dialect.MySQL8Dialect
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQL8Dialect

# -----------------------------------Redis specific configuration-----------------------------------
# REDIS_ENABLED: false
# REDIS_HOST: "localhost"
# REDIS_PORT: 6379
# REDIS_USERNAME: 
# REDIS_PASSWORD: 