server:
  port: 8085

jwt.secret: 'local'

# Database configuration flags
DATABASE_TYPE: 'h2'

# Common datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        webAllowOthers: true
        autostart: true
  boot:
    admin:
      client:
        url: url
        enable: false
        auto-registration: true
        instance:
          name: Dns-manager

# actuator
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

# -----------------------------------H2 specific configuration-----------------------------------

H2_DB: '/config/Coding/dns-manager-workspace/db/h2'
H2_USERNAME: 'sa'
H2_PASSWORD: 'password'

# -----------------------------------MySQL specific configuration-----------------------------------

MYSQL_HOST: '10.24.24.2'
MYSQL_PORT: 3306
MYSQL_DB: 'Dns_manager'
MYSQL_USERNAME: 'dns_manager'
MYSQL_PASSWORD: 'dns_manager'
MYSQL_USE_SSL: 'false'

# -----------------------------------Redis specific configuration-----------------------------------
REDIS_ENABLED: true
REDIS_HOST: "10.24.24.2"
REDIS_PORT: 6379
REDIS_USERNAME: 
REDIS_PASSWORD: 
